-- ============================================================================
-- Reabilitah — Prontuário Eletrônico CERLUZ (Centro de Recuperação Luz no Vale)
-- Schema PostgreSQL — consolidação de rascunho-tabelas.txt e rascunho-tabelas-2.txt
--
-- Fontes: CLAUDE.md (regras), documentos-mapeados.md (campos reais dos 17
--         documentos), GUIA-IMPLEMENTACAO.md (fases), PADRAO-BACKEND-NESTJS.md.
--
-- Convenções (mesmas do rascunho do time):
--   - Nomes em MAIÚSCULO e sem aspas. O PostgreSQL guarda tudo em minúsculo,
--     o que casa com a SnakeNamingStrategy do TypeORM (paciente.nome_completo).
--   - Tabela no singular; FK = NOME_DA_TABELA + _ID.
--   - Datas: DT_ prefixo. Data civil = DATE; momento exato = TIMESTAMPTZ.
--   - Nenhum CHECK. Coluna com lista fixa de valores é VARCHAR comum, com as
--     opções no comentário; quem valida é o backend (DTO/enum do NestJS).
--   - Lista que a instituição pode editar vira tabela de apoio.
--   - Nada é apagado: ATIVO + DT_DESATIVADO (CLAUDE.md §7). Nenhum ON DELETE
--     CASCADE em histórico.
--
-- Assinatura (CLAUDE.md §6): manuscrita no papel impresso. O sistema gera o PDF
-- e guarda a DIGITALIZAÇÃO do papel assinado. Não existe tabela ASSINATURA por
-- assinante, nem METODO_ASSINATURA, nem captura de traço.
--
-- Arquivos (PDF gerado e digitalizações) NÃO ficam no banco: ver DOCUMENTO_ARQUIVO.
-- ============================================================================


-- ============================================================================
-- 1. TABELAS DE APOIO
-- ============================================================================

CREATE TABLE CARGO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME                    VARCHAR(80)  NOT NULL UNIQUE
    -- Coordenador, Psicóloga, Enfermeiro, Monitor, Administrativo, Diretor...
);

CREATE TABLE TIPO_DEPENDENCIA (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME                    VARCHAR(80)  NOT NULL UNIQUE,
    ORDEM                   SMALLINT     NOT NULL DEFAULT 0
    -- Lista fixa de 10, igual à da Ficha de Acolhimento em papel.
);

CREATE TABLE PERMISSAO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO                  VARCHAR(60)  NOT NULL UNIQUE,  -- 'documentos.criar': é o que o código testa
    NOME                    VARCHAR(120) NOT NULL          -- 'Criar documentos': é o que a tela mostra
    -- Não existe permissão de editar documento: documento é imutável (§7).
);

CREATE TABLE LAYOUT_EMISSOR (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO                  VARCHAR(30)  NOT NULL UNIQUE,
    -- INSTITUCIONAL | INSTITUCIONAL_SIMPLES | ESTADUAL
    NOME                    VARCHAR(80)  NOT NULL,
    CABECALHO_ARQUIVO       TEXT,
    RODAPE_ARQUIVO          TEXT,
    TEXTO_RODAPE            TEXT,
    DT_ATUALIZACAO          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    -- Os 3 timbres do papel: institucional completo, só logo, e brasão do
    -- Governo de SC. O layout é por emissor, não global (CLAUDE.md §8.1-d).
);


-- ============================================================================
-- 2. ACESSO E EQUIPE
-- ============================================================================

-- Identidade de login, sem saber de quem é. Hoje só profissional tem login;
-- se um dia o paciente puder entrar, ele ganha PACIENTE.USUARIO_ID e esta
-- tabela não muda.
CREATE TABLE USUARIO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMAIL                   VARCHAR(120) NOT NULL UNIQUE,
    SENHA                   VARCHAR(100) NOT NULL,       -- hash bcrypt, nunca a senha
    ADMIN                   BOOLEAN      NOT NULL DEFAULT FALSE,
    ATIVO                   BOOLEAN      NOT NULL DEFAULT TRUE,  -- pode entrar no sistema
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    DT_DESATIVADO           TIMESTAMPTZ
);

-- A pessoa da equipe. É daqui que sai o nome exibido como autor em todo o
-- histórico, e os aniversariantes do dashboard. Pode existir sem login.
CREATE TABLE PROFISSIONAL (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USUARIO_ID              INTEGER      UNIQUE REFERENCES USUARIO (ID),  -- NULL = sem acesso
    NOME                    VARCHAR(120) NOT NULL,
    TELEFONE                VARCHAR(20),
    CARGO_ID                INTEGER      NOT NULL REFERENCES CARGO (ID),
    REG_PROFISSIONAL        VARCHAR(30),                 -- COREN, CRP, CRM...
    CPF                     VARCHAR(14)  UNIQUE,
    RG                      VARCHAR(20),
    ENDERECO_RUA            VARCHAR(150),
    ENDERECO_NR             VARCHAR(10),
    ENDERECO_BAIRRO         VARCHAR(80),
    ENDERECO_MUNICIPIO      VARCHAR(80),
    ENDERECO_ESTADO         VARCHAR(2),
    DT_NASC                 DATE,                        -- aniversariantes no dashboard
    ATIVO                   BOOLEAN      NOT NULL DEFAULT TRUE,  -- faz parte da equipe
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    DT_DESATIVADO           TIMESTAMPTZ
    -- Profissional desativado continua aparecendo no histórico com o nome real,
    -- nunca como "usuário desconhecido" (CLAUDE.md §7).
);

CREATE TABLE USUARIO_PERMISSAO (
    USUARIO_ID              INTEGER      NOT NULL REFERENCES USUARIO (ID),
    PERMISSAO_ID            INTEGER      NOT NULL REFERENCES PERMISSAO (ID),
    PRIMARY KEY (USUARIO_ID, PERMISSAO_ID)
);


-- ============================================================================
-- 3. PACIENTE
-- ============================================================================

-- Cadastro do paciente: editável e completado aos poucos. Só o nome é obrigatório.
-- As datas de acolhimento e desligamento, o convênio e a chave SISREG são
-- digitados aqui (é o que a capa do prontuário registra no papel) e alimentam
-- os documentos na hora de gerar.
CREATE TABLE PACIENTE (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME_COMPLETO           VARCHAR(150) NOT NULL,
    APELIDO                 VARCHAR(80),                 -- [CONFIRMAR] não existe no papel
    CPF                     VARCHAR(14),
    RG                      VARCHAR(20),
    DT_NASCIMENTO           DATE,                        -- idade é calculada, não guardada
    NACIONALIDADE           VARCHAR(60),
    ESTADO_ORIGEM           VARCHAR(2),
    MUNICIPIO_ORIGEM        VARCHAR(80),
    NOME_PAI                VARCHAR(150),
    NOME_MAE                VARCHAR(150),
    ESCOLARIDADE            VARCHAR(60),
    PROFISSAO               VARCHAR(80),
    COR_RACA                VARCHAR(30),
    ESTADO_CIVIL            VARCHAR(30),
    FILHOS                  BOOLEAN,
    ENDERECO_RUA            VARCHAR(150),
    ENDERECO_NR             VARCHAR(10),
    ENDERECO_BAIRRO         VARCHAR(80),
    ENDERECO_MUNICIPIO      VARCHAR(80),
    ENDERECO_ESTADO         VARCHAR(2),
    -- primeira droga: no papel é texto livre + idade, não data nem FK
    PRI_DEPENDENCIA_LICITA        VARCHAR(80),
    IDADE_PRI_DEPENDENCIA_LICITA  SMALLINT,
    PRI_DEPENDENCIA_ILICITA       VARCHAR(80),
    IDADE_PRI_DEPENDENCIA_ILICITA SMALLINT,
    -- internação atual (capa do prontuário)
    DT_ACOLHIMENTO          DATE,
    DT_DESLIGAMENTO         DATE,                        -- NULL = está internado
    CONVENIO                VARCHAR(80),                 -- 'Governo do Estado de SC', particular...
    CHAVE_SISREG            VARCHAR(40),                 -- exigida nos 4 documentos da GERSA
    ATIVO                   BOOLEAN      NOT NULL DEFAULT TRUE,  -- cadastro ativo, não internação
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    DT_DESATIVADO           TIMESTAMPTZ
    -- Readmissão: as datas são atualizadas no cadastro. O histórico da
    -- internação anterior continua nos documentos daquele período.
);

CREATE TABLE PACIENTE_DEPENDENCIA (
    PACIENTE_ID             INTEGER      NOT NULL REFERENCES PACIENTE (ID),
    TIPO_DEPENDENCIA_ID     INTEGER      NOT NULL REFERENCES TIPO_DEPENDENCIA (ID),
    PRIMARY KEY (PACIENTE_ID, TIPO_DEPENDENCIA_ID)
    -- Faltava no rascunho: no papel é seleção múltipla.
);

CREATE TABLE RESPONSAVEL (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PACIENTE_ID             INTEGER      NOT NULL REFERENCES PACIENTE (ID),
    NOME                    VARCHAR(150) NOT NULL,
    PARENTESCO              VARCHAR(60),
    CPF                     VARCHAR(14),
    RG                      VARCHAR(20),
    TELEFONE                VARCHAR(20),
    ENDERECO                VARCHAR(200),
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    -- Um paciente pode ter mais de um responsável.
);


-- ============================================================================
-- 4. MOTOR DE DOCUMENTOS (o tipo de documento é dado, não código)
-- ============================================================================

CREATE TABLE TIPO_DOCUMENTO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO                  VARCHAR(60)  NOT NULL UNIQUE,   -- 'ficha-acolhimento'
    NOME                    VARCHAR(120) NOT NULL,
    NOME_EXIBICAO           VARCHAR(150) NOT NULL,          -- 'Termo de Acolhimento (SES/SC)'
    EMISSOR                 VARCHAR(20)  NOT NULL,
    -- INSTITUCIONAL | ESTADUAL
    CATEGORIA               VARCHAR(20)  NOT NULL,
    -- ADMINISTRATIVO | ENFERMAGEM | CLINICO | PSICOLOGICO | JURIDICO
    FORMATO                 VARCHAR(20)  NOT NULL DEFAULT 'FOLHA_UNICA',
    -- FOLHA_UNICA | FOLHA_TABELA
    LAYOUT_EMISSOR_ID       INTEGER      REFERENCES LAYOUT_EMISSOR (ID),
    TEXTO_FIXO              TEXT,                           -- Regimento Interno, termos de ciência
    ASSINANTES              JSONB,
    -- Rótulos das linhas de assinatura impressas no PDF, em ordem. Ex.:
    --   ["Assinatura do Acolhido", "Responsável pelo Acolhido", "Monitor Responsável"]
    -- Vazio ou nulo = tipo não exige assinatura (documento nasce CONCLUIDO).
    -- A assinatura é a caneta, então isto é só o que vai impresso no papel.
    VERSAO                  INTEGER      NOT NULL DEFAULT 1,
    DESCRICAO               TEXT,
    ATIVO                   BOOLEAN      NOT NULL DEFAULT TRUE,
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    DT_DESATIVADO           TIMESTAMPTZ
);

CREATE TABLE CAMPO_TIPO_DOCUMENTO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIPO_DOCUMENTO_ID       INTEGER      NOT NULL REFERENCES TIPO_DOCUMENTO (ID),
    CAMPO                   VARCHAR(60)  NOT NULL,          -- chave dentro de DOCUMENTO.DADOS
    ROTULO                  VARCHAR(150) NOT NULL,          -- texto exibido, igual ao papel
    TIPO_CAMPO              VARCHAR(20)  NOT NULL,
    -- TEXTO_CURTO | TEXTO_LONGO | DATA | NUMERO | SELECAO_UNICA |
    -- SELECAO_MULTIPLA | BOOLEANO
    OBRIGATORIO             BOOLEAN      NOT NULL DEFAULT FALSE,
    ORDEM                   SMALLINT     NOT NULL,
    GRUPO                   VARCHAR(60),                    -- 'Sinais Vitais', 'Cabeça'
    TEXTO_AJUDA             TEXT,                           -- o texto entre parênteses do papel
    OPCOES                  JSONB,                          -- para os campos de seleção
    UNIQUE (TIPO_DOCUMENTO_ID, CAMPO)
);


-- ============================================================================
-- 5. DOCUMENTOS EMITIDOS
-- ============================================================================

CREATE SEQUENCE SEQ_DOCUMENTO_CODIGO START 1;

-- O conteúdo (DADOS) é gravado uma vez e nunca muda: não existe edição (§7).
-- Corrigir = novo documento. As ações ficam em DOCUMENTO_EVENTO.
-- Em tipo FOLHA_TABELA, as linhas da folha ficam como lista dentro de DADOS.
CREATE TABLE DOCUMENTO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO                  VARCHAR(20)  NOT NULL UNIQUE
        DEFAULT ('DOC-' || LPAD(NEXTVAL('SEQ_DOCUMENTO_CODIGO')::TEXT, 6, '0')),
    TIPO_DOCUMENTO_ID       INTEGER      NOT NULL REFERENCES TIPO_DOCUMENTO (ID),
    PACIENTE_ID             INTEGER      NOT NULL REFERENCES PACIENTE (ID),
    DADOS                   JSONB        NOT NULL DEFAULT '{}'::JSONB,
    HASH_CONTEUDO           CHAR(64)     NOT NULL,          -- SHA-256 de DADOS
    STATUS                  VARCHAR(30)  NOT NULL DEFAULT 'PENDENTE_ASSINATURA',
    -- PENDENTE_ASSINATURA  aguardando o papel assinado voltar
    -- ASSINADO             digitalização anexada
    -- CONCLUIDO            tipo que não exige assinatura
    -- DESATIVADO           desativado com justificativa
    VERSAO                  INTEGER      NOT NULL DEFAULT 1,
    SUBSTITUI_DOCUMENTO_ID  INTEGER      REFERENCES DOCUMENTO (ID),
    PROFISSIONAL_ID         INTEGER      NOT NULL REFERENCES PROFISSIONAL (ID), -- quem criou
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    DT_DESATIVADO           TIMESTAMPTZ
);

-- PDF gerado para impressão e digitalizações do papel assinado a caneta.
-- Substitui a antiga tabela ASSINATURA: quem assinou está no papel.
--
-- O ARQUIVO EM SI NÃO FICA NO BANCO. CAMINHO guarda onde ele está: o caminho
-- relativo dentro do diretório de armazenamento (STORAGE_DIR) quando o sistema
-- roda em servidor próprio, ou a chave do objeto quando for storage externo.
-- O banco guarda só os metadados, e o backend serve o arquivo por rota
-- autenticada — nunca por URL pública.
CREATE TABLE DOCUMENTO_ARQUIVO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOCUMENTO_ID            INTEGER      NOT NULL REFERENCES DOCUMENTO (ID),
    NUMERO_VERSAO           INTEGER      NOT NULL,          -- versão que foi impressa/assinada
    TIPO                    VARCHAR(20)  NOT NULL,
    -- PDF_GERADO | DIGITALIZACAO
    CAMINHO                 TEXT         NOT NULL,          -- gerado pelo sistema, nunca o nome enviado
    NOME_ORIGINAL           VARCHAR(255),                   -- só para exibir
    MIME_TYPE               VARCHAR(60)  NOT NULL,
    -- application/pdf | image/jpeg | image/png
    TAMANHO_BYTES           INTEGER      NOT NULL,
    HASH_ARQUIVO            CHAR(64)     NOT NULL,          -- SHA-256: integridade e duplicata
    SUBSTITUI_ARQUIVO_ID    INTEGER      REFERENCES DOCUMENTO_ARQUIVO (ID),
    ATIVO                   BOOLEAN      NOT NULL DEFAULT TRUE,  -- FALSE = foi substituído
    PROFISSIONAL_ID         INTEGER      NOT NULL REFERENCES PROFISSIONAL (ID), -- quem enviou
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    -- Digitalização ilegível não é apagada: envia-se outra, com justificativa.
);

-- Linha do tempo do documento: é o que a aba Auditoria mostra.
-- Não confundir com LOG: isto é histórico de prontuário, nunca é limpo.
CREATE TABLE DOCUMENTO_EVENTO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOCUMENTO_ID            INTEGER      NOT NULL REFERENCES DOCUMENTO (ID),
    NUMERO_VERSAO           INTEGER      NOT NULL,
    ACAO                    VARCHAR(30)  NOT NULL,
    -- CRIACAO | PDF_BAIXADO | DIGITALIZACAO_ANEXADA |
    -- DIGITALIZACAO_SUBSTITUIDA | DESATIVACAO | REATIVACAO
    JUSTIFICATIVA           TEXT,                           -- obrigatória ao desativar/reativar/substituir
    DOCUMENTO_ARQUIVO_ID    INTEGER      REFERENCES DOCUMENTO_ARQUIVO (ID),
    PROFISSIONAL_ID         INTEGER      NOT NULL REFERENCES PROFISSIONAL (ID),
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- 6. APOIO AO SISTEMA
-- ============================================================================

-- Quadro de avisos do dashboard: recado da equipe com prazo de validade.
CREATE TABLE AVISO (
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MENSAGEM                TEXT         NOT NULL,
    PROFISSIONAL_ID         INTEGER      NOT NULL REFERENCES PROFISSIONAL (ID),
    DT_INICIO               DATE         NOT NULL DEFAULT CURRENT_DATE,
    DT_FIM                  DATE         NOT NULL,
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Log técnico único do sistema inteiro: erros, login, ações de qualquer módulo.
-- Serve para diagnóstico, não é histórico de prontuário (esse é DOCUMENTO_EVENTO).
CREATE TABLE LOG (
    ID                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIPO                    VARCHAR(20)  NOT NULL,
    -- EVENTO | ERRO
    MODULO                  VARCHAR(40)  NOT NULL,
    -- AUTH | PACIENTE | DOCUMENTO | ARQUIVO | PDF | EQUIPE | SISTEMA
    USUARIO_ID              INTEGER      REFERENCES USUARIO (ID),  -- NULL = ação do sistema
    DESCRICAO               TEXT         NOT NULL,          -- texto livre montado no código
    DT_CRIACAO              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    -- Nunca gravar senha, token ou dado de prontuário na descrição.
);


-- ============================================================================
-- 7. ÍNDICES DE CONSULTA
-- ============================================================================

CREATE INDEX IX_PROFISSIONAL_CARGO        ON PROFISSIONAL (CARGO_ID);
CREATE INDEX IX_RESPONSAVEL_PACIENTE      ON RESPONSAVEL (PACIENTE_ID);
CREATE INDEX IX_DOCUMENTO_PACIENTE        ON DOCUMENTO (PACIENTE_ID);
CREATE INDEX IX_DOCUMENTO_TIPO            ON DOCUMENTO (TIPO_DOCUMENTO_ID);
CREATE INDEX IX_DOCUMENTO_STATUS          ON DOCUMENTO (STATUS);
CREATE INDEX IX_DOCUMENTO_ARQUIVO_DOC     ON DOCUMENTO_ARQUIVO (DOCUMENTO_ID);
CREATE INDEX IX_DOCUMENTO_EVENTO_DOC      ON DOCUMENTO_EVENTO (DOCUMENTO_ID);
CREATE INDEX IX_CAMPO_TIPO_DOCUMENTO      ON CAMPO_TIPO_DOCUMENTO (TIPO_DOCUMENTO_ID);
CREATE INDEX IX_LOG_MODULO                ON LOG (MODULO, DT_CRIACAO);

-- Busca por nome de paciente sem diferenciar maiúsculas
CREATE INDEX IX_PACIENTE_NOME             ON PACIENTE (LOWER(NOME_COMPLETO));

-- Busca por conteúdo do documento na central de documentos
CREATE INDEX IX_DOCUMENTO_DADOS           ON DOCUMENTO USING GIN (DADOS);
